name: CI

on: [push, pull_request]

jobs:
  build_mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grab latest libspng
        run: |
          curl https://github.com/randy408/libspng/archive/v0.7.4.zip >v0.7.4.zip
          Expand-Archive -Force "v0.7.4.zip" "%~dp0libspng"
      - name: Install libspng
        run: |
          cd libspng
          cp spng/spng.c ../lib/src
          cp spng/spng.h ../lib/src/include
      - name: Build the dingus
        run: |
          sed -i '1s/^/#define SPNG__BUILD\n/' lib/src/include/spngwrapper.h
          make
          mkdir -p out
          mv bin/hxconv.exe out/
          mv lib/bin/libhmxobj.dll out/
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: Win64Latest
          path: out
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install -y zlib1g-dev gcc make unzip
      - name: spng a bitch
        run: |
          wget https://github.com/randy408/libspng/archive/v0.7.4.zip 
          unzip v0.7.4.zip -d libspng
          cp libspng/libspng-0.7.4/spng/spng.c lib/src
          cp libspng/libspng-0.7.4/spng/spng.h lib/src/include
      - name: Build the dingus
        run: |
          sed -i '1s/^/#define SPNG__BUILD\n/' lib/src/include/spngwrapper.h
          sed -i 's/-lspng//g' Makefile
          make
          mkdir -p out
          mv bin/hxconv out/
          mv lib/bin/libhmxobj.so out/
          echo "#!/usr/bin/sh\
          mv libhmxobj.so /usr/lib/\
          mv hxconv /usr/bin" >SUDOME_INSTALL.sh
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: LinuxLatest
          path: out